
### Tablas ###

# Tabla usuarios
DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE USUARIOS(

	ID_USUARIO INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(20) NOT NULL,
    PASSWD VARCHAR(64) NOT NULL,	-- TODO: revisar contrasinal

    UNIQUE INDEX AK_NOME(NOME),
    
    PRIMARY KEY (ID_USUARIO)

)ENGINE = INNODB;



# Tabla eventos
DROP TABLE IF EXISTS EVENTOS;
CREATE TABLE EVENTOS(
	
    ID_EVENTO INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(25) NOT NULL,
    DATA_EVENTO DATE NOT NULL,
    HORA TIME NULL,

	INDEX INDEX_DATA_EVENTO(DATA_EVENTO),   -- > Xa que se van facer bastantes consultas ao redor da data do evento

	PRIMARY KEY (ID_EVENTO)

) ENGINE = INNODB;



# Tabla de eventos privados co usuario que creou o evento 
DROP TABLE IF EXISTS EVENTOS_PRIVADOS;
CREATE TABLE EVENTOS_PRIVADOS(

	EVENTO INT UNSIGNED NOT NULL,
    USUARIO INT UNSIGNED NOT NULL,
    
    FOREIGN KEY (EVENTO) REFERENCES EVENTOS(ID_EVENTO)
		ON DELETE RESTRICT		-- NO SEGURO DE ESTA PARTE 
        ON UPDATE CASCADE,
        
    INDEX FK_EVENTO(EVENTO),

	FOREIGN KEY (USUARIO) REFERENCES USUARIOS(ID_USUARIO)
		ON DELETE CASCADE
        ON UPDATE CASCADE,

    INDEX FK_USUARIO(USUARIO),
    
    PRIMARY KEY (EVENTO, USUARIO)

)ENGINE = INNODB;



# Tabla de eventos grupais e o seu creador (o único usuario que pode borrar o evento)
DROP TABLE IF EXISTS EVENTOS_GRUPAIS;
CREATE TABLE EVENTOS_GRUPAIS(

	EVENTO INT UNSIGNED NOT NULL,
    CREADOR INT UNSIGNED NOT NULL,
    
    FOREIGN KEY (EVENTO) REFERENCES EVENTOS(ID_EVENTO)
		ON DELETE CASCADE
        ON UPDATE CASCADE,

    INDEX FK_EVENTO(EVENTO),
        
	FOREIGN KEY (CREADOR) REFERENCES USUARIOS(ID_USUARIO)
		ON DELETE CASCADE
        ON UPDATE CASCADE,

    INDEX FK_CREADOR(USUARIO),
    
    PRIMARY KEY (EVENTO, CREADOR)

)ENGINE=INNODB;



# Tabla de eventos publicos
DROP TABLE IF EXISTS EVENTOS_PUBLICOS;
CREATE TABLE EVENTOS_PUBLICOS(

    EVENTO INT UNSIGNED NOT NULL,
    CREADOR INT UNSIGNED NOT NULL,

    FOREIGN KEY (EVENTO) REFERENCES EVENTOS(ID_EVENTO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    
    INDEX FK_EVENTO(EVENTO),

    FOREIGN KEY (CREADOR) REFERENCES USUARIOS(ID_USUARIO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    INDEX FK_CREADOR(USUARIO),

    PRIMARY KEY (EVENTO)

)ENGINE = INNODB;



# Tabla para gardar que usuarios participan en determinado evento grupal

	# IMPORTANTE: o creador tamén rexstrado como usuario participante no evento 

DROP TABLE IF EXISTS GRUPAIS_USUARIOS;
CREATE TABLE GRUPAIS_USUARIOS(

	EVENTO_GRUPAL INT UNSIGNED NOT NULL,
    USUARIO INT UNSIGNED NOT NULL,
    
    FOREIGN KEY (EVENTO_GRUPAL) REFERENCES EVENTOS_GRUPAIS(EVENTO)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	
    INDEX FK_EVENTO_GRUPAL(EVENTO_GRUPAL),
	
    FOREIGN KEY (USUARO) REFERENCES USUARIOS(ID_USUARIO)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
        
	INDEX FK_USUARIO(USUARIO),
    
    PRIMARY KEY (EVENTO, USUARIO)

);



### Vistas ###

-- bc mercedes likes vistas && son rápidas